### ISSUE TITLE
Is it possibe to pass a static list of items to pick from?

### ISSUE THREAD

**Issue by madelaney** [axkirillov/easypick.nvim#13]
I was trying to follow some of your examples but instead of having a command that would generate the list, have a static list of values to send in.

One example is a download to select a color scheme to apply. I tried the following config but it did not work:
```lua
local status_ok, easypick = pcall(require, 'easypick')
if not status_ok then
  return
end

local supported_color_scheme = {
  'Darktheme',
  'SimpleThme',
  'AnotherThme',
}

easypick.setup({
  pickers = {
    {
      name = 'ColorScheme',
      values = supported_color_scheme,
      action = easypick.actions.nvim_command('FloatermNew colorscheme'),
      opts = require('telescope.themes').get_dropdown({}),
    },
  },
})

```

**Comment by axkirillov** [comment]
Hello! It is possible indeed, but not quite this way 😄 
Easypick does not accept a "values" opt, as you are doing in your example. Instead it has to be done through the "command" opt.
The [wiki](https://github.com/axkirillov/easypick.nvim/wiki) has an example for exactly this scenario.
```lua
-- a list of commands that you want to pick from
local list = [[
<< EOF
Darktheme
SimpleThme
AnotherThme
EOF
]]

easypick.setup({
  pickers = {
    {
      name = "colorscheme",
      command = "cat " .. list,
      action = easypick.actions.nvim_command("colorscheme"),
      opts = require('telescope.themes').get_dropdown({})
    }
  }
})
``` 
I removed the 'FloatermNew' from the prefix, since it seems to me you just want to call the builtin coloscheme command and not call "colorscheme" in the shell in a new floating terminal window.

**Comment by madelaney** [comment]
@axkirillov , awesome. Thank you for the example and details. This is exactly what I was looking for.
