### ISSUE TITLE
Can we do same concept but with vim commands?

### ISSUE THREAD

**Issue by GitMurf** [axkirillov/easypick.nvim#15]
Can we do same concept but with vim commands? In other words, lets say I want to get run a command like `:changes` to see all my changes in my buffer or maybe `:jumps` to get list of my jump list.

Essentially the same concept but instead of console commands, it would be with vim commands.

1. is that possible today with this plugin?
2. is this something you would consider adding if it is not currently possible?

Thanks!

**Comment by axkirillov** [comment]
Hi! 
I think this would be out of scope for easypick because all it does is parse the **shell command output**, as stated in the description. Doing this for vim commands would involve some clever trickery, that I don't feel confident to do. I am also not sure whether it would be worth the effort, since not all commands have an output or output something that would make sense as a picker.
Another point is, there is actually a `jumplist` picker already! You can look or it by just running :Telescope
and here is the code for it
```lua
internal.jumplist = function(opts)
  opts = opts or {}
  local jumplist = vim.fn.getjumplist()[1]

  -- reverse the list
  local sorted_jumplist = {}
  for i = #jumplist, 1, -1 do
    if vim.api.nvim_buf_is_valid(jumplist[i].bufnr) then
      jumplist[i].text = vim.api.nvim_buf_get_lines(jumplist[i].bufnr, jumplist[i].lnum - 1, jumplist[i].lnum, false)[1]
        or ""
      table.insert(sorted_jumplist, jumplist[i])
    end
  end

  pickers
    .new(opts, {
      prompt_title = "Jumplist",
      finder = finders.new_table {
        results = sorted_jumplist,
        entry_maker = make_entry.gen_from_quickfix(opts),
      },
      previewer = conf.qflist_previewer(opts),
      sorter = conf.generic_sorter(opts),
    })
    :find()
end
``` 
As you can see, it uses `vim.fn.getjumplist()[1]`, which is not exactly a generic solution 😅
This on the other hand `make_entry.gen_from_quickfix(opts)` looks generic, so you could probably extract it and make a plugin that creates pickers from quicklists (and call it `pickle.nvim`!), I'm not sure whether it would make sense, but even if it would, it wouldn't fit into easypicks paradigm.
