### ISSUE TITLE
Can we provide how to run the command? Like which shell to use?

### ISSUE THREAD

**Issue by GitMurf** [axkirillov/easypick.nvim#16]
I am on Windows and the default shell is cmd.exe (Windows command prompt) which has some limitations, especially when trying to get outputs (using echo etc.) to be used for the Telescope picker.

Is there a way we can set the shell to use so that I could run using powershell / pwsh?

**Comment by GitMurf** [comment]
As a side note, it took me a while to figure out that the examples in the README were likely for mac/unix as things like `ls` and the git changed files examples don't work with cmd.exe (Windows command prompt). It would be nice to have some examples that work for Windows and/or a footnote about the examples being for unix. Thanks!

**Comment by axkirillov** [comment]
So firstly, I think easypick will just use whatever shell you nvim is running in, although I didn't test it myself. But it definitely won't work with powershell, simply because it's a structured shell. This is sort of evident, when you read the readme here
https://github.com/axkirillov/easypick.nvim/blob/6ea5aef3eceba46a26091e2339c9b51d7e104648/README.md?plain=1#L25
The output of the comand has to be plain text. So yes, there is an implicit assumption that you are running a posix-like shell, but it has little to do with the host os. After all, you can run bash on Windows as well.

Considering examples, I think it's not unreasonable to assume that the users of easypick should have minimal technical knowledge about how shells work. Again, having the ls command does not tie you to a specific host system, and it is probably one of the most widely known and used shell commands ever. But even without having to run it, I know exactly how the output looks like, just because I've seen it a billion times. I imagine that I am sharing this experience with the majority of Neovim users.

Another reason I don't want to add any windows examples is that I don't use windows and I can't test it, but even more, I don't have any idea about Windows in the first place, so I wouldn't be able to write those examples.
